sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t RudiSpaans/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true -t RudiSpaans/docker-react npm run test

